defaults:
  - defaults

command: "training"
# continue_from_checkpoint: null
# continue_from_checkpoint: "/workspace/mnt/storage/zhangjunkang/zjk_fileSystem/github/silk/assets/models/silk/coco-rgb-aug.ckpt"
# continue_from_checkpoint: "/workspace/mnt/storage/zhangjunkang/zjk_fileSystem/github/silk/output/silk/train_log/2023-05-28-baseline/08-15-39/lightning_logs/version_0/checkpoints/epoch=9-step=39999.ckpt"
# continue_from_checkpoint: "/workspace/mnt/storage/zhangjunkang/zjk_fileSystem/github/silk/var/silk-cli/run/training/2023-05-30/13-09-08-asset/lightning_logs/version_0/checkpoints/epoch=9-step=31679.ckpt"
# continue_from_checkpoint: "/workspace/mnt/storage/zhangjunkang/zjk_fileSystem/github/silk/var/silk-cli/run/training/2023-06-02/10-06-17/lightning_logs/version_0/checkpoints/epoch=0-step=3167.ckpt"
continue_from_checkpoint: "/workspace/mnt/storage/zhangjunkang/zjk_fileSystem/github/silk/var/silk-cli/run/training/2023-06-25/08-59-10/lightning_logs/version_0/checkpoints/epoch=9-step=70339.ckpt"
model: ???
trainer:
  strategy: ddp
  _target_: pytorch_lightning.Trainer
  gpus: ${ref:default.ngpus}
  # change benchmark to False if your model input size changes between iterations
  benchmark: true
loaders:
  training:
    _target_: torch.utils.data.DataLoader
    dataset: ???
    num_workers: ${ref:default.loader.training.workers}
  validation:
    _target_: torch.utils.data.DataLoader
    dataset: ???
    num_workers: ${ref:default.loader.validation.workers}
    shuffle: false
