defaults:
  - defaults
  - _self_

# root: /workspace/mnt/storage/zhangjunkang/zjk1/data/colmap_gaosu/sample_data
# listFile: /workspace/mnt/storage/zhangjunkang/zjk1/data/colmap_gaosu/sample_data/img_list_all.txt
# gaosu_day + coco2017
root: /workspace/mnt/storage/zhangjunkang/zjk1/data
# listFile: /workspace/mnt/storage/zhangjunkang/zjk1/data/coco_train2017_and_gaosu_day_list.txt
listFile: /workspace/mnt/storage/zhangjunkang/zjk1/data/coco_train2017_2W_and_gaosu_day_list.txt
